name: Build Cross-build environment for pyodide-build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: build-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-xbuildenv.yml
