name: Build Cross-build environment for pyodide-build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to build'
        default: 'main'
        required: false

permissions: {}

concurrency:
  group: build-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
    name: Build cross-build environment for Pyodide
    uses: ./.github/workflows/build-xbuildenv.yml
    with:
      branch: ${{ github.event.inputs.branch || 'main' }}
